In [87]:
import numpy as np

In [88]:
from numpy.linalg import eigh, norm
from scipy.linalg import cho_factor, cho_solve

## 1. Eigen-decomposition

A@V = Lambda@V

In [89]:
A = np.array([
    [4, 2],
    [-5, -3]
])
A

array([[ 4,  2],
       [-5, -3]])

In [90]:
lambdas, V = np.linalg.eig(A)

In [91]:
lambdas

array([ 2., -1.])

In [92]:
V

array([[ 0.70710678, -0.37139068],
       [-0.70710678,  0.92847669]])

In [93]:
Vinv = np.linalg.inv(V)
Vinv

array([[2.3570226 , 0.94280904],
       [1.79505494, 1.79505494]])

In [94]:
Lambda = np.diag(lambdas)
Lambda

array([[ 2.,  0.],
       [ 0., -1.]])

In [95]:
A_hat = V@Lambda@Vinv
A_hat

array([[ 4.,  2.],
       [-5., -3.]])

In [96]:
np.allclose(A, A_hat)

True

## 2. Singular value decomposition (SVD)

In [97]:
# A = U@D@V.T is the SVD

In [98]:
A = np.array([
    [-5, 2, 3],
    [2, 5, 1],
    [-3, 1, -5]
])

In [99]:
A.T @ A

array([[38, -3,  2],
       [-3, 30,  6],
       [ 2,  6, 35]])

In [100]:
ev, V = eigh(A.T@A)

In [101]:
ev

array([25., 39., 39.])

In [102]:
V

array([[ 0.26726124, -0.96362411,  0.        ],
       [ 0.80178373,  0.22237479,  0.5547002 ],
       [-0.53452248, -0.14824986,  0.83205029]])

In [103]:
V[:,0] # First column - first egein vector

array([ 0.26726124,  0.80178373, -0.53452248])

In [104]:
u0 = A@V[:,0] / norm(A@V[:,0])
u1 = A@V[:,1] / norm(A@V[:,1])
u2 = A@V[:,2] / norm(A@V[:,2])

In [105]:
U = np.array([u0, u1, u2]).T
U

array([[-0.26726124,  0.77151675,  0.57735027],
       [ 0.80178373, -0.15430335,  0.57735027],
       [ 0.53452248,  0.6172134 , -0.57735027]])

In [106]:
D = np.round(U.T@A@V, decimals=5)
D

array([[ 5.   ,  0.   , -0.   ],
       [-0.   ,  6.245, -0.   ],
       [-0.   , -0.   ,  6.245]])

In [107]:
A_hat = np.round(U@D@V.T, decimals=0)
A_hat

array([[-5.,  2.,  3.],
       [ 2.,  5.,  1.],
       [-3.,  1., -5.]])

##### np.linalg.eig vs np.linalg.eigh
https://stackoverflow.com/questions/45434989/numpy-difference-between-linalg-eig-and-linalg-eigh

In [126]:
a = np.random.rand(3,3)  # generate a random array shaped (3,3)
a = (a + a.T)/2  # a becomes a random simmetric matrix   
# a = a@a.T
evalues1, evectors1 = np.linalg.eig(a)
evalues2, evectors2 = np.linalg.eigh(a)
print(evalues1)
print(evalues2)
print(evectors1)
print(evectors2)

[1.31367001 0.47909889 0.15672581]
[0.15672581 0.47909889 1.31367001]
[[ 0.6599121   0.74008385  0.12958363]
 [ 0.42772861 -0.22825489 -0.87461302]
 [ 0.61770888 -0.63259434  0.4671832 ]]
[[ 0.12958363 -0.74008385 -0.6599121 ]
 [-0.87461302  0.22825489 -0.42772861]
 [ 0.4671832   0.63259434 -0.61770888]]


## 3. Cholesky Decomposition

Decompose a diagnal matrix A into the product of a lower triangle maxtrix L and its transpose.

A = L@L.T

In [108]:
np.random.seed(1234)
X = np.round(np.random.normal(size=(5,5)), decimals=2)
A = X@X.T
A

array([[ 4.2964,  0.0863,  1.5847,  0.6336, -0.1578],
       [ 0.0863,  6.9593,  1.9657,  3.6654, -3.813 ],
       [ 1.5847,  1.9657,  7.3944, -1.4735, -2.2495],
       [ 0.6336,  3.6654, -1.4735,  4.3971, -1.5355],
       [-0.1578, -3.813 , -2.2495, -1.5355,  2.5566]])

In [109]:
L = np.linalg.cholesky(A)
L

array([[ 2.07277592,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.04163499,  2.63771995,  0.        ,  0.        ,  0.        ],
       [ 0.7645303 ,  0.73315925,  2.50447019,  0.        ,  0.        ],
       [ 0.30567704,  1.38478429, -1.08704299,  1.09743863,  0.        ],
       [-0.07612979, -1.44436499, -0.45213032, -0.00326217,  0.51007997]])

In [110]:
L@L.T

array([[ 4.2964,  0.0863,  1.5847,  0.6336, -0.1578],
       [ 0.0863,  6.9593,  1.9657,  3.6654, -3.813 ],
       [ 1.5847,  1.9657,  7.3944, -1.4735, -2.2495],
       [ 0.6336,  3.6654, -1.4735,  4.3971, -1.5355],
       [-0.1578, -3.813 , -2.2495, -1.5355,  2.5566]])

In [111]:
(A - L@L.T).sum()

8.881784197001252e-16

In [112]:
b = np.random.normal(size=(5,1))
b

array([[-0.46930528],
       [ 0.67555409],
       [-1.81702723],
       [-0.18310854],
       [ 1.05896919]])

#### Solve x (a column vector) for: A@x = b

In [113]:
# Option 1 with numpy
x1 = np.linalg.solve(A, b)
print(x1)
# Option 2 with scipy
L = cho_factor(A, lower=True)
x2 = cho_solve(L, b)
print(x2)

np.allclose(x1, x2)

[[ 0.13624971]
 [ 2.92071015]
 [ 0.00602437]
 [-1.04186471]
 [ 4.15822019]]
[[ 0.13624971]
 [ 2.92071015]
 [ 0.00602437]
 [-1.04186471]
 [ 4.15822019]]


True

#### A set of correlated variables to covariance matrix 

The covariance of a random variable $X$ and $Y$ (mean - and variance 1) is given by, 

$$
\mbox{cov}(X, Y) = \mathbb{E}(XY^\dagger).
$$

So if we have a collection of uncorrelated, noramlly distributed random variables,

$$
\mbox{cov}(X_i, X_j) = \delta_{i,j} = I
$$

Suppose we have a set of correlated variables to covariance matrix $C$.  We can do a Cholesky decomposition and write $C = LL^\dagger$.

Suppose we have two random variables in $V$ and $U$ is defined such that $U = LV$.  What is the covariance?


$$
\mathbb{E}(UU^\dagger) = \mathbb{E}( (LV)(LV)^\dagger) ) = \mathbb{E}(LVV^\dagger L^\dagger)
$$
We can factor out $L$,

$$
L\mathbb{E}(VV^\dagger)L^\dagger = LIL^\dagger = LL^\dagger = C
$$

In [114]:
np.random.seed(18)

X = np.random.normal(size=(1000_000, ))
Y = np.random.normal(size=(1000_000, ))

np.cov(X, Y)

array([[ 9.99689376e-01, -4.13407355e-04],
       [-4.13407355e-04,  9.99733468e-01]])

In [115]:
C = np.array([
    [1, 0.5],
    [0.5, 1]
])

In [116]:
X.shape = (1, X.size)
Y.shape = (1, Y.size)
XY = np.vstack((X,Y))
XY.shape

(2, 1000000)

In [117]:
L = np.linalg.cholesky(C)

In [118]:
UV = L @ XY

U = UV[0, :]
V = UV[1, :]

print(np.cov(U, V))

[[0.99968938 0.49948667]
 [0.49948667 0.99936442]]


References:

https://github.com/kpmooney/numerical_methods_youtube/blob/master/matrix_decomposition/Cholesky%20Decomposition.ipynb