In [1]:
import numpy as np

In [2]:
from numpy.linalg import eigh, norm

# Singular value decomposition (SVD)

In [20]:
# A = U@D@V.T is the SVD

In [21]:
A = np.array([
    [-5, 2, 3],
    [2, 5, 1],
    [-3, 1, -5]
])

In [22]:
A.T @ A

array([[38, -3,  2],
       [-3, 30,  6],
       [ 2,  6, 35]])

In [23]:
ev, V = eigh(A.T@A)

In [24]:
ev

array([25., 39., 39.])

In [25]:
V

array([[ 0.26726124, -0.96362411,  0.        ],
       [ 0.80178373,  0.22237479,  0.5547002 ],
       [-0.53452248, -0.14824986,  0.83205029]])

In [26]:
V[:,0] # First column - first egein vector

array([ 0.26726124,  0.80178373, -0.53452248])

In [27]:
u0 = A@V[:,0] / norm(A@V[:,0])
u1 = A@V[:,1] / norm(A@V[:,1])
u2 = A@V[:,2] / norm(A@V[:,2])

In [33]:
U = np.array([u0, u1, u2]).T
U

array([[-0.26726124,  0.77151675,  0.57735027],
       [ 0.80178373, -0.15430335,  0.57735027],
       [ 0.53452248,  0.6172134 , -0.57735027]])

In [32]:
D = np.round(U.T@A@V, decimals=5)
D

array([[ 5.   ,  0.   , -0.   ],
       [-0.   ,  6.245, -0.   ],
       [-0.   , -0.   ,  6.245]])

In [36]:
A_hat = np.round(U@D@V.T, decimals=0)
A_hat

array([[-5.,  2.,  3.],
       [ 2.,  5.,  1.],
       [-3.,  1., -5.]])

## Cholesky Decomposition